package grammar;

public interface Constants extends ScannerConstants, ParserConstants
{
    int EPSILON  = 0;
    int DOLLAR   = 1;

    int t_INT_LIT = 2;
    int t_FLOAT_LIT = 3;
    int t_BIN_LIT = 4;
    int t_HEX_LIT = 5;
    int t_STRING_LIT = 6;
    int t_CHAR_LIT = 7;
    int t_RB_OPEN = 8;
    int t_RB_CLOSE = 9;
    int t_SB_OPEN = 10;
    int t_SB_CLOSE = 11;
    int t_CB_OPEN = 12;
    int t_CB_CLOSE = 13;
    int t_INCREMENT = 14;
    int t_DECREMENT = 15;
    int t_PLUS = 16;
    int t_MINUS = 17;
    int t_DIV = 18;
    int t_MULT = 19;
    int t_COMMA = 20;
    int t_MOD = 21;
    int t_COLON = 22;
    int t_END = 23;
    int t_GT = 24;
    int t_LT = 25;
    int t_GTE = 26;
    int t_LTE = 27;
    int t_EQ = 28;
    int t_NEQ = 29;
    int t_ASSIGN = 30;
    int t_M_COMMENT = 31;
    int t_COMMENT = 32;
    int t_SHIFT_RIGHT = 33;
    int t_SHIFT_LEFT = 34;
    int t_BIT_AND = 35;
    int t_BIT_OR = 36;
    int t_BIT_NOT = 37;
    int t_BIT_XOR = 38;
    int t_AND = 39;
    int t_OR = 40;
    int t_NOT = 41;
    int t_VOID = 42;
    int t_INT = 43;
    int t_FLOAT = 44;
    int t_STRING = 45;
    int t_BOOL = 46;
    int t_CHAR = 47;
    int t_FUNC = 48;
    int t_RETURN = 49;
    int t_GIVES = 50;
    int t_BACK = 51;
    int t_IF = 52;
    int t_ELSE = 53;
    int t_FALSE = 54;
    int t_TRUE = 55;
    int t_WHILE = 56;
    int t_FOR = 57;
    int t_EACH = 58;
    int t_OF = 59;
    int t_DO = 60;
    int t_READ = 61;
    int t_WRITE = 62;
    int t_ID = 63;

}
